services:
  pgadmin:
    image: thajeztah/pgadmin4
    network_mode: host
    volumes:
      - pgvolume:/pgdata

  db:
    # build: ./db
    image: postgres:13-alpine
    ports:
      - 5437:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fastapi_project
      - POSTGRES_HOST=127.0.0.1
    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build: ./api
    volumes:
      - ./api:/var/task
    working_dir: /var/task
    ports: 
      - "8000:8000"
    entrypoint: ["poetry", "run"] 
    command: ["uvicorn", "main:app", "--reload", "--host=0.0.0.0"]


  web:
    build: .
    volumes:
      - ./web:/src/web
    working_dir: /src/web
    user: "${COMPOSE_UID:-1000}:${COMPOSE_GID:-1000}"
    ports:
      - 3030:8080
    command: ["npm", "run", "serve"]


volumes:
  db-data:
    driver: local
  pgvolume:
    driver: local